name: CI

on:
  push:
    branches:
      - "main"

jobs:
  release-and-zip:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Zip file structure for Assignment
        run: zip -r Assignment-2.zip beamer/presentation.pdf conv-harness.c Makefile tests/ tex/documentation.pdf

      - name: Commit and push
          uses: EndBug/add-and-commit@v7
          with:
            add: '["Assignment-2.zip"]'
            message: 'My commit message'
            push: true
      
